server:
  port: 8080
  servlet:
    context-path: /telaCotacoes



spring:
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_bootcamp
    username: postgres
    password: admin
   
  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    
    hibernate:
      ddl-auto: none

application:
  description: Projeto tela de cotações
